In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../deshimula_all_reviews.csv')
df.head()

,id,company_name,developer_role,date,title,content,upvote,downvote,comment_count,vibe
0,1,Betopia / BdCalling / Sparktech / Softvence / ...,NaN,"February 04, 2026",Behind the Noise: Freshers Get Real Wings Here...,I've been working at $parktech (under Betopi@ ...,1,14,8,Positive
1,2,Betopia / BdCalling / Sparktech / Softvence / ...,NaN,"January 11, 2026",My Personal Experience at Sp@rkTech Agency (Pa...,I have seen many negative comments about Betop...,1,24,20,Positive
2,3,Betopia / BdCalling / Sparktech / Softvence / ...,NaN,"January 10, 2026",Hard Work + Smart Work = Success,Betopi@ / BdCa11ing / $parktech / S0ftv3nce / ...,3,31,11,Positive
3,4,Betopia / BdCalling / Sparktech / Softvence / ...,NaN,"June 10, 2025",Good for freshers,Pros\nThis company is good for freshers who ha...,1,25,6,Positive
4,5,Betopia / BdCalling / Sparktech / Softvence / ...,NaN,"June 08, 2025",Supportive Work Environment with Strong Growth...,Pros:\nSupportive Management: Encouraging and ...,0,46,10,Positive

In [7]:
sentiment_df.shape

(2552, 2)

In [3]:
sentiment_df = df[['content', 'vibe']]
sentiment_df.vibe.value_counts()

vibe
Negative    1980
Positive     289
Mixed        283
Name: count, dtype: int64

In [4]:
sentiment_df.to_csv('sentiment_df.csv', index=False)

In [5]:
sentiment_df.head(10)

                                             content      vibe
0  I've been working at $parktech (under Betopi@ ...  Positive
1  I have seen many negative comments about Betop...  Positive
2  Betopi@ / BdCa11ing / $parktech / S0ftv3nce / ...  Positive
3  Pros\nThis company is good for freshers who ha...  Positive
4  Pros:\nSupportive Management: Encouraging and ...  Positive
5  আজ ৫ ই আগষ্ট। বাংলাদেশে সরকারি সাধারণ ছুটি। সব...  Negative
6  কী আর বলব এদের নিয়ে! আমি এখানে আড়াই বছরেরও ব...  Negative
7  বাংলাদেশ শ্রম আইন, ২০০৬ অনুযায়ী প্রতিটি প্রতিষ...  Negative
8  $oftvence-এ ইনক্রিমেন্ট নিতে গিয়ে বুঝলাম, একজ...  Negative
9  $oftvence-এ হঠাৎ করেই WhatsApp গ্রুপে একটি নোট...  Negative

In [6]:
sentiment_top_10 = sentiment_df.head(10)
sentiment_top_10.to_csv('sentiment_top_10.csv', index=False)